### ISSUE TITLE
Permission denied if TINYOWS_CATCH_SEGV enabled

### ISSUE THREAD

**Issue by drnextgis** [camptocamp/docker-tinyows#10]
Relevant part of my docker-compose.yaml:

```
tinyows:
  image: camptocamp/tinyows:master
  environment:
    TINYOWS_CATCH_SEGV: '1'
    SEGFAULT_SIGNALS: 'all'
  links:
    - db
  ports:
    - "8380:80"
  volumes:
    - ./tinyows.xml:/etc/mapserver/tinyows.xml
 ```
 
 Error message:
 ```
 tinyows_1  | /usr/local/bin/tinyows-wrapper: line 7: /var/log/tinyows.log: Permission denied
 ```

**Comment by yjacolin** [comment]
What is the relevant part of tinyows.xml for the log configuration? I think you defined /var/log/tinyows.log which is not a good practise for docker container as it could increase the size of the container, and you can lose the log after a crash.

You should redirect the log toward stderror (I don't know if it possible for tinyows) the other way will be to mount an external volume from your docker-compose.yml.

**Comment by drnextgis** [comment]
Log file path is defined here: https://github.com/camptocamp/docker-tinyows/blob/7db4343aa827ac2c738d28125501933466a9621d/runtime/usr/local/bin/tinyows-wrapper#L7

**Comment by yjacolin** [comment]
hum good catch. I will investigate. But my comments is still correct. We need probably document this.

Y.

**Comment by yjacolin** [comment]
Here my docker-compose.yaml file:

```
 version: '2.0'
 
 services:
   tinyows:
     image: camptocamp/tinyows:master
     environment:
       TINYOWS_CATCH_SEGV: '1'
       SEGFAULT_SIGNALS: 'all'
     ports:
       - "8380:80"
     volumes:
       - ./tinyows.xml:/etc/mapserver/tinyows.xml
```
Then:
```
$ docker-compose up 
Recreating tmp_tinyows_1 ... done
Attaching to tmp_tinyows_1
tinyows_1  | Listening on /var/log/tinyows.log
tinyows_1  |  [notice] [pid 15] AH00489: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
tinyows_1  |  [notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Could you try with the simplest docker-compose.yaml file and find what the relevant part trigger this error?

Could you check image ID : 601f197393c8 (with `docker images` command)

**Comment by drnextgis** [comment]
@yjacolin have you tried to make a request?

1. Run tinyows:

```
$ docker images | grep camptocamp      
camptocamp/tinyows                     master                     604bb0b5b75b   19 hours ago    157MB

$ docker-compose up  
Creating app_db_1 ... done
Creating app_tinyows_1 ... done
Attaching to app_db_1, app_tinyows_1
tinyows_1  | Listening on /var/log/tinyows.log
tinyows_1  |  [notice] [pid 15] AH00489: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
tinyows_1  |  [notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'
```

2. Make a request:
```
$ curl "http://localhost:8380/?service=wfs&version=1.1.0&request=GetCapabilities"
```

3. Check the logs:
```
tinyows_1  | /usr/local/bin/tinyows-wrapper: line 7: /var/log/tinyows.log: Permission denied
tinyows_1  |  [warn] [pid 18] mod_fcgid: error reading data from FastCGI server
tinyows_1  |  [error] [pid 18] End of script output before headers: tinyows-wrapper
tinyows_1  | 100435 - 172.17.0.1 - - [17/Jun/2021:21:44:37 +0000] "GET /?service=wfs&version=1.1.0&request=GetCapabilities HTTP/1.1" 500 801 "" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"
```

docker-compose.yaml:

```
tinyows:
  image: camptocamp/tinyows:master
  environment:
    TINYOWS_CATCH_SEGV: '1'
    SEGFAULT_SIGNALS: 'all'
  links:
    - db
  ports:
    - "8380:80"
  volumes:
    - ./tinyows.xml:/etc/mapserver/tinyows.xml

db:
  image: postgis/postgis:12-2.5
  volumes:
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
```
